"""Assemble index.html from the template and the JSON data files.

    python3 build_site.py

Reads (all next to this script's parent):
  scripts/template.html      page shell with __DECK_JSON__ / __OVERRIDES_JSON__ / __ABOUT_JSON__ tokens
  data/deck_data.json        slide content, generated by extract_pptx.py from source-pptx/
  data/overrides.json        hand-authored fixes layered on top of deck_data.json in the browser
  data/about.json            "About the course" page content

Writes:
  index.html                 self-contained, no build step needed to view it

There is no content processing here on purpose: the template's own JavaScript
merges overrides.json over deck_data.json at page load, so re-running
extract_pptx.py never disturbs the hand-authored fixes.
"""

import json
import os

BASE = os.path.dirname(__file__)
ROOT = os.path.join(BASE, "..")


def load(*parts):
    path = os.path.join(ROOT, *parts)
    with open(path, encoding="utf-8") as f:
        text = f.read()
    if path.endswith(".json"):
        json.loads(text)  # fail loudly on malformed JSON
    return text


template = load("scripts", "template.html")
deck_json = load("data", "deck_data.json")
overrides_json = load("data", "overrides.json")
about_json = load("data", "about.json")

html = (
    template
    .replace("__DECK_JSON__", deck_json)
    .replace("__OVERRIDES_JSON__", overrides_json)
    .replace("__ABOUT_JSON__", about_json)
)

out = os.path.join(ROOT, "index.html")
with open(out, "w", encoding="utf-8") as f:
    f.write(html)

print("wrote", os.path.relpath(out, ROOT), "-", round(os.path.getsize(out) / 1024 / 1024, 2), "MB")
